### ISSUE TITLE
依赖位置

### ISSUE THREAD

**Issue by jimixy** [JinJieTan/react-webpack#4]
"devDependencies": {
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "pubsub-js": "^1.7.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-hot-loader": "^4.8.4",
    "react-lazy-load": "^3.0.13",
    "react-lazyload": "^2.5.0",
    "react-lazyload-fadein": "^1.1.0",
    "react-loadable": "^5.5.0",
    "react-redux": "^7.0.3",
    "react-router-dom": "^5.0.0",
    "react-scroll": "^1.7.11",
    "react-virtualized": "^9.21.1",
    "react-virtualized-auto-sizer": "^1.0.2",
    "react-window": "^1.8.5",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "axios": "^0.18.0"
  },
这些不是应该放到dependencies里面吗？

**Comment by JinJieTan** [comment]
你好，今晚我会重新归纳依赖。之前放错了。

**Comment by JinJieTan** [comment]
已经修复，
Mac 请使用 $ sudo cnpm I 命令下载依赖

windos 请使用 cnpm i 命令下载依赖
