### ISSUE TITLE
一些webpack配置建议

### ISSUE THREAD

**Issue by mumofa** [JinJieTan/react-webpack#5]
1、正常webpack配置除了 dev 和 prod 两份外 还有一份 webpack.base.js 做公共配置项， 感觉作者可以考虑抽一下公共配置出来

2、一开始首页我看见是有写css module的 然后开发发现并没有 看了下更新日志和配置 才发现关了，所以感觉又可以专门弄个 config文件夹 专门放这些配置项

**Comment by JinJieTan** [comment]
本项目只是为了阐述从零打造一个webpack配置，就是为了降低难度不想进行高度封装，不然我一个文件就可以开发和生产环境一起用。
