### ISSUE TITLE
html-loader & html-webpack-plugin功能不是一致么

### ISSUE THREAD

**Issue by tylerrrkd** [JinJieTan/react-webpack#6]
RT,

为啥有了`html-webpack-plugin`之后还要在`babel`里用`html-loader`呢？

**Comment by JinJieTan** [comment]
html-loader是为了让webpack认识html结尾的文件&nbsp;


html-webpack-plugin是为了让webpack以这个html为模板对后期打包对js文件进行引入


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kaida Lin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月3日(星期二) 下午2:57
收件人:&nbsp;"JinJieTan/react-webpack"<react-webpack@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[JinJieTan/react-webpack] html-loader &amp; html-webpack-plugin功能不是一致么 (#6)




RT,
 
为啥有了html-webpack-plugin之后还要在babel里用html-loader呢？

**Comment by tylerrrkd** [comment]
Thank you
